### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by stoelwinder** [trevorsharp/youtube-podcast-feeds#16]
After successfully installing the Docker instance and uploading a test config.json, I managed to get it to run without throwing any errors. However when accessing port 80, I get a blank page with title ERROR and text:

Cannot Get /

My config.json is as follows:
{
  "hostname" : "http://IPADDRESS",
  "apiKey" : "APIKEY",
  "timeZone" : "Asia/Singapore",
  "updateInterval" : 2,
  "maxResults": 5,
  "maxEpisodes" : 10,
  "feeds" : [
    {
      "id" : "Ignbeyond",
      "title" : "IGN Beyond",
      "channel" : "UCmajVTORW3vp5qM8r0myznA"
    }
  ]
}

Data Folder has 2 subfolders:
content (empty)
ignbeyond (contains cover.png and feedData.json)

feedData.json contains what appears to be a number of video entries, but they are not downloaded nor are they displayed in the web interface.

**Comment by trevorsharp** [comment]
The route you want to look at is http://IPADDRESS/Ignbeyond — This _should_ return the RSS feed for those videos.

FYI: To have videos download, you will have to set the “highQualityVideo” option to true.

**Comment by trevorsharp** [comment]
The latest version has been updated to serve a homepage that should give you a list of the RSS feed URLs. You can pull the latest image from docker and see if that helps out as well

**Comment by stoelwinder** [comment]
Thank you, that worked!
