### ISSUE TITLE
Support for multiple YouTube API keys

### ISSUE THREAD

**Issue by 726a67** [trevorsharp/youtube-podcast-feeds#22]
Currently, only a single YouTube API key can be provided for use with the application. In order to extend API usage (beyond the default 10,000 queries/day limit) for configurations with many feeds and/or many queries per day, it would be useful if multiple API keys could be provided and rotated through in round-robin fashion.

**Comment by trevorsharp** [comment]
I would prefer to avoid the need to support multiple API keys as I can understand why YouTube has these quotas in place. I've made some changes in the latest update to reduce (potentially significantly) the amount of API calls needed to accomplish the same functionality. Hopefully these improvements, along with some adjustment of your `updateInterval` and `maxResults` settings, can provide you with a workable solution within the limits of the API quotas. If not, you could run multiple instances with different API keys and split up your feeds between them.

**Comment by 726a67** [comment]
That's reasonable. I'll keep an eye on the updated API usage metrics, but either way thanks for the quick turnaround!

**Comment by 726a67** [comment]
Just wanted to follow up to let you know that your API usage optimizations have reduced my daily API calls by 83%! Awesome work.
